CREATE TABLE IF NOT EXISTS SHIPWRECK(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(500),
    SHIP_CONDITION VARCHAR(255),
    DEPTH INT,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    YEAR_DISCOVERED INT
);

INSERT INTO SHIPWRECK (ID, DEPTH, DESCRIPTION, LATITUDE, LONGITUDE, NAME, SHIP_CONDITION, YEAR_DISCOVERED) VALUES
(1, 360, 'nice ship but at the bottom :) ', 51.623, 42.52035, 'Ship 1', 'old but gold', 2009),
(2, 981, 'cool and hot ', 43.1245, 42.8571, 'mahna mahna', 'with muppets inside', 1996);
