CREATE TABLE IF NOT EXISTS SHIPWRECK(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(500),
    `SHIP_CONDITION` VARCHAR(255),
    DEPTH INT,
    LATITUDE DOUBLE,
    LONGTITUDE DOUBLE,
    YEAR_DISCOVERED INT
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;